-- =====================================================================
-- Servus — Seed
-- Sem dados de demonstração. Adicione aqui apenas dados reais/iniciais
-- se necessário (roda com o papel `postgres`, ignorando RLS).
-- =====================================================================
